[package]
name = "nutp"
version = "0.1.0"
edition = "2021"
licence = "MIT"
keywords = ["UART", "no_std"]
repository = "https://github.com/Cethannel/nutp"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.14.2", features = ["alloc"] }
